# Generated by Django 3.0.8 on 2020-07-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answerKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionID', models.CharField(max_length=20, verbose_name='ansID')),
                ('answer', models.CharField(max_length=100, verbose_name='dataString')),
                ('page', models.IntegerField(verbose_name='pageNum')),
            ],
        ),
    ]
