# Generated by Django 3.0.8 on 2020-07-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klein', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerkey',
            old_name='ID',
            new_name='questionID',
        ),
    ]
