# Generated by Django 3.0.8 on 2020-07-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klein', '0002_auto_20200724_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerkey',
            name='questionID',
            field=models.CharField(max_length=20, verbose_name='ansID'),
        ),
    ]
